version: '2'

services:

  elasticsearch:
    environment: 
      ES_JAVA_OPTS: "-Xmx2g -Xms2g" 
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data

  logstash:
    networks:
      - localdev
    environment: 
      ES_JAVA_OPTS: "-Xmx500m -Xms500m" 
  
networks:
  localdev:
    external: true
