version: '2'

services:

  elasticsearch:
    image: "${COMPOSE_REGISTRY}/elasticsearch:${COMPOSE_TAG}"
    restart: unless-stopped
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx30g -Xms30g"
      KIBANA_USER_PASSWORD:
      LOGSTASH_SYSTEM_USER_PASSWORD:
      ELASTIC_USER_PASSWORD:
      ELASTIC_INDEX_PREFIX:
      DEFAULT_NUMBER_OF_SHARDS:
      DEFAULT_NUMBER_OF_REPLICAS:
    networks:
      - elk

  logstash:
    image: "${COMPOSE_REGISTRY}/logstash:${COMPOSE_TAG}"
    restart: unless-stopped
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
      - "9191:9191"
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
      ELASTIC_USER_PASSWORD:
      ELASTIC_INDEX_PREFIX:
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: "${COMPOSE_REGISTRY}/kibana:${COMPOSE_TAG}"
    restart: unless-stopped
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_PASSWORD: "${KIBANA_USER_PASSWORD}"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
    